# /etc/haproxy/haproxy.cfg 

global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 2048
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11
    tune.ssl.default-dh-param 2048

defaults
    log     global
    mode    tcp
    option  dontlognull
    timeout connect 5s
    timeout client  1m
    timeout server  1m

frontend fe_tls_443
    bind *:443 ssl crt /etc/letsencrypt/live/fh.peterkappus.com/fullchain.pem crt-key /etc/letsencrypt/live/fh.peterkappus.com/privkey.pem
    tcp-request inspect-delay 5s
    tcp-request content accept if { req_ssl_hello_type 1 }

    # Route SSH by SNI to ssh backend; web to nginx
    use_backend be_ssh if { req.ssl_sni -i ssh.fh.peterkappus.com }
    use_backend be_web if { req.ssl_sni -i fh.peterkappus.com }

    default_backend be_web

backend be_ssh
    mode tcp
    server ssh_local 127.0.0.1:22

backend be_web
    mode tcp
    server web_local 127.0.0.1:8443